#!/bin/bash                                                                     
                                                                                   
# Read in one character from the user (this may be 'Y', 'y', 'N', 'n'). If the character is 'Y' or 'y' display "YES". If the character is 'N' or 'n' display "NO". No other character will be provided as input.
                                                                                   
read CHAR                                                                          
if [ $CHAR == 'Y' ] || [ $CHAR == 'y' ]                                            
then                                                                               
    echo 'YES'                                                                     
elif [ $CHAR == 'N' ] || [ $CHAR == 'n' ]                                          
then                                                                               
    echo 'NO'                                                                      
else                                                                               
    exit 1                                                                         
fi  
